// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: distraccion.proto

package distraccion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DistraccionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProbExito     int32                  `protobuf:"varint,1,opt,name=probExito,proto3" json:"probExito,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionRequest) Reset() {
	*x = DistraccionRequest{}
	mi := &file_distraccion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionRequest) ProtoMessage() {}

func (x *DistraccionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_distraccion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionRequest.ProtoReflect.Descriptor instead.
func (*DistraccionRequest) Descriptor() ([]byte, []int) {
	return file_distraccion_proto_rawDescGZIP(), []int{0}
}

func (x *DistraccionRequest) GetProbExito() int32 {
	if x != nil {
		return x.ProbExito
	}
	return 0
}

type DistraccionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Confirmacion  bool                   `protobuf:"varint,1,opt,name=confirmacion,proto3" json:"confirmacion,omitempty"`
	Exito         bool                   `protobuf:"varint,2,opt,name=exito,proto3" json:"exito,omitempty"`
	Motivo        string                 `protobuf:"bytes,3,opt,name=motivo,proto3" json:"motivo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DistraccionResponse) Reset() {
	*x = DistraccionResponse{}
	mi := &file_distraccion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DistraccionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DistraccionResponse) ProtoMessage() {}

func (x *DistraccionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_distraccion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DistraccionResponse.ProtoReflect.Descriptor instead.
func (*DistraccionResponse) Descriptor() ([]byte, []int) {
	return file_distraccion_proto_rawDescGZIP(), []int{1}
}

func (x *DistraccionResponse) GetConfirmacion() bool {
	if x != nil {
		return x.Confirmacion
	}
	return false
}

func (x *DistraccionResponse) GetExito() bool {
	if x != nil {
		return x.Exito
	}
	return false
}

func (x *DistraccionResponse) GetMotivo() string {
	if x != nil {
		return x.Motivo
	}
	return ""
}

var File_distraccion_proto protoreflect.FileDescriptor

const file_distraccion_proto_rawDesc = "" +
	"\n" +
	"\x11distraccion.proto\x12\vdistraccion\"2\n" +
	"\x12DistraccionRequest\x12\x1c\n" +
	"\tprobExito\x18\x01 \x01(\x05R\tprobExito\"g\n" +
	"\x13DistraccionResponse\x12\"\n" +
	"\fconfirmacion\x18\x01 \x01(\bR\fconfirmacion\x12\x14\n" +
	"\x05exito\x18\x02 \x01(\bR\x05exito\x12\x16\n" +
	"\x06motivo\x18\x03 \x01(\tR\x06motivo2f\n" +
	"\vDistraccion\x12W\n" +
	"\x12IniciarDistraccion\x12\x1f.distraccion.DistraccionRequest\x1a .distraccion.DistraccionResponseB\x0eZ\f/distraccionb\x06proto3"

var (
	file_distraccion_proto_rawDescOnce sync.Once
	file_distraccion_proto_rawDescData []byte
)

func file_distraccion_proto_rawDescGZIP() []byte {
	file_distraccion_proto_rawDescOnce.Do(func() {
		file_distraccion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_distraccion_proto_rawDesc), len(file_distraccion_proto_rawDesc)))
	})
	return file_distraccion_proto_rawDescData
}

var file_distraccion_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_distraccion_proto_goTypes = []any{
	(*DistraccionRequest)(nil),  // 0: distraccion.DistraccionRequest
	(*DistraccionResponse)(nil), // 1: distraccion.DistraccionResponse
}
var file_distraccion_proto_depIdxs = []int32{
	0, // 0: distraccion.Distraccion.IniciarDistraccion:input_type -> distraccion.DistraccionRequest
	1, // 1: distraccion.Distraccion.IniciarDistraccion:output_type -> distraccion.DistraccionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_distraccion_proto_init() }
func file_distraccion_proto_init() {
	if File_distraccion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_distraccion_proto_rawDesc), len(file_distraccion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_distraccion_proto_goTypes,
		DependencyIndexes: file_distraccion_proto_depIdxs,
		MessageInfos:      file_distraccion_proto_msgTypes,
	}.Build()
	File_distraccion_proto = out.File
	file_distraccion_proto_goTypes = nil
	file_distraccion_proto_depIdxs = nil
}
