docker-michael:
	docker compose up --build michael

docker-lester:
	docker compose up --build lester

docker-franklin:
	docker compose up --build franklin

docker-trevor:
	docker compose up --build trevor

docker-turnoff:
	@echo "🛑 Parando toda la infraestructura..."
	docker compose down

