// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: negociacion.proto

package negociacion

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Solicitar contrato
type ContratoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContratoRequest) Reset() {
	*x = ContratoRequest{}
	mi := &file_negociacion_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContratoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContratoRequest) ProtoMessage() {}

func (x *ContratoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_negociacion_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContratoRequest.ProtoReflect.Descriptor instead.
func (*ContratoRequest) Descriptor() ([]byte, []int) {
	return file_negociacion_proto_rawDescGZIP(), []int{0}
}

type ContratoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Botin             int32                  `protobuf:"varint,1,opt,name=botin,proto3" json:"botin,omitempty"`
	ProbExitoFranklin int32                  `protobuf:"varint,2,opt,name=probExitoFranklin,proto3" json:"probExitoFranklin,omitempty"`
	ProbExitoTrevor   int32                  `protobuf:"varint,3,opt,name=probExitoTrevor,proto3" json:"probExitoTrevor,omitempty"`
	RiesgoPolicial    int32                  `protobuf:"varint,4,opt,name=riesgoPolicial,proto3" json:"riesgoPolicial,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ContratoResponse) Reset() {
	*x = ContratoResponse{}
	mi := &file_negociacion_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContratoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContratoResponse) ProtoMessage() {}

func (x *ContratoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_negociacion_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContratoResponse.ProtoReflect.Descriptor instead.
func (*ContratoResponse) Descriptor() ([]byte, []int) {
	return file_negociacion_proto_rawDescGZIP(), []int{1}
}

func (x *ContratoResponse) GetBotin() int32 {
	if x != nil {
		return x.Botin
	}
	return 0
}

func (x *ContratoResponse) GetProbExitoFranklin() int32 {
	if x != nil {
		return x.ProbExitoFranklin
	}
	return 0
}

func (x *ContratoResponse) GetProbExitoTrevor() int32 {
	if x != nil {
		return x.ProbExitoTrevor
	}
	return 0
}

func (x *ContratoResponse) GetRiesgoPolicial() int32 {
	if x != nil {
		return x.RiesgoPolicial
	}
	return 0
}

// Aceptar o rechazar contrato
type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_negociacion_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_negociacion_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_negociacion_proto_rawDescGZIP(), []int{2}
}

type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_negociacion_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_negociacion_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_negociacion_proto_rawDescGZIP(), []int{3}
}

var File_negociacion_proto protoreflect.FileDescriptor

const file_negociacion_proto_rawDesc = "" +
	"\n" +
	"\x11negociacion.proto\x12\vnegociacion\"\x11\n" +
	"\x0fContratoRequest\"\xa8\x01\n" +
	"\x10ContratoResponse\x12\x14\n" +
	"\x05botin\x18\x01 \x01(\x05R\x05botin\x12,\n" +
	"\x11probExitoFranklin\x18\x02 \x01(\x05R\x11probExitoFranklin\x12(\n" +
	"\x0fprobExitoTrevor\x18\x03 \x01(\x05R\x0fprobExitoTrevor\x12&\n" +
	"\x0eriesgoPolicial\x18\x04 \x01(\x05R\x0eriesgoPolicial\"\x11\n" +
	"\x0fDecisionRequest\"\x12\n" +
	"\x10DecisionResponse2\x80\x02\n" +
	"\vNegociacion\x12P\n" +
	"\x11SolicitarContrato\x12\x1c.negociacion.ContratoRequest\x1a\x1d.negociacion.ContratoResponse\x12N\n" +
	"\x0fAceptarContrato\x12\x1c.negociacion.DecisionRequest\x1a\x1d.negociacion.DecisionResponse\x12O\n" +
	"\x10RechazarContrato\x12\x1c.negociacion.DecisionRequest\x1a\x1d.negociacion.DecisionResponseB\x0eZ\f/negociacionb\x06proto3"

var (
	file_negociacion_proto_rawDescOnce sync.Once
	file_negociacion_proto_rawDescData []byte
)

func file_negociacion_proto_rawDescGZIP() []byte {
	file_negociacion_proto_rawDescOnce.Do(func() {
		file_negociacion_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_negociacion_proto_rawDesc), len(file_negociacion_proto_rawDesc)))
	})
	return file_negociacion_proto_rawDescData
}

var file_negociacion_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_negociacion_proto_goTypes = []any{
	(*ContratoRequest)(nil),  // 0: negociacion.ContratoRequest
	(*ContratoResponse)(nil), // 1: negociacion.ContratoResponse
	(*DecisionRequest)(nil),  // 2: negociacion.DecisionRequest
	(*DecisionResponse)(nil), // 3: negociacion.DecisionResponse
}
var file_negociacion_proto_depIdxs = []int32{
	0, // 0: negociacion.Negociacion.SolicitarContrato:input_type -> negociacion.ContratoRequest
	2, // 1: negociacion.Negociacion.AceptarContrato:input_type -> negociacion.DecisionRequest
	2, // 2: negociacion.Negociacion.RechazarContrato:input_type -> negociacion.DecisionRequest
	1, // 3: negociacion.Negociacion.SolicitarContrato:output_type -> negociacion.ContratoResponse
	3, // 4: negociacion.Negociacion.AceptarContrato:output_type -> negociacion.DecisionResponse
	3, // 5: negociacion.Negociacion.RechazarContrato:output_type -> negociacion.DecisionResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_negociacion_proto_init() }
func file_negociacion_proto_init() {
	if File_negociacion_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_negociacion_proto_rawDesc), len(file_negociacion_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_negociacion_proto_goTypes,
		DependencyIndexes: file_negociacion_proto_depIdxs,
		MessageInfos:      file_negociacion_proto_msgTypes,
	}.Build()
	File_negociacion_proto = out.File
	file_negociacion_proto_goTypes = nil
	file_negociacion_proto_depIdxs = nil
}
