// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: negociacion.proto

package negociacion

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Negociacion_SolicitarContrato_FullMethodName = "/negociacion.Negociacion/SolicitarContrato"
	Negociacion_AceptarContrato_FullMethodName   = "/negociacion.Negociacion/AceptarContrato"
	Negociacion_RechazarContrato_FullMethodName  = "/negociacion.Negociacion/RechazarContrato"
)

// NegociacionClient is the client API for Negociacion service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NegociacionClient interface {
	SolicitarContrato(ctx context.Context, in *ContratoRequest, opts ...grpc.CallOption) (*ContratoResponse, error)
	AceptarContrato(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
	RechazarContrato(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type negociacionClient struct {
	cc grpc.ClientConnInterface
}

func NewNegociacionClient(cc grpc.ClientConnInterface) NegociacionClient {
	return &negociacionClient{cc}
}

func (c *negociacionClient) SolicitarContrato(ctx context.Context, in *ContratoRequest, opts ...grpc.CallOption) (*ContratoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ContratoResponse)
	err := c.cc.Invoke(ctx, Negociacion_SolicitarContrato_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negociacionClient) AceptarContrato(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, Negociacion_AceptarContrato_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *negociacionClient) RechazarContrato(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, Negociacion_RechazarContrato_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NegociacionServer is the server API for Negociacion service.
// All implementations must embed UnimplementedNegociacionServer
// for forward compatibility.
type NegociacionServer interface {
	SolicitarContrato(context.Context, *ContratoRequest) (*ContratoResponse, error)
	AceptarContrato(context.Context, *DecisionRequest) (*DecisionResponse, error)
	RechazarContrato(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedNegociacionServer()
}

// UnimplementedNegociacionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNegociacionServer struct{}

func (UnimplementedNegociacionServer) SolicitarContrato(context.Context, *ContratoRequest) (*ContratoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolicitarContrato not implemented")
}
func (UnimplementedNegociacionServer) AceptarContrato(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AceptarContrato not implemented")
}
func (UnimplementedNegociacionServer) RechazarContrato(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RechazarContrato not implemented")
}
func (UnimplementedNegociacionServer) mustEmbedUnimplementedNegociacionServer() {}
func (UnimplementedNegociacionServer) testEmbeddedByValue()                     {}

// UnsafeNegociacionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NegociacionServer will
// result in compilation errors.
type UnsafeNegociacionServer interface {
	mustEmbedUnimplementedNegociacionServer()
}

func RegisterNegociacionServer(s grpc.ServiceRegistrar, srv NegociacionServer) {
	// If the following call pancis, it indicates UnimplementedNegociacionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Negociacion_ServiceDesc, srv)
}

func _Negociacion_SolicitarContrato_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContratoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegociacionServer).SolicitarContrato(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Negociacion_SolicitarContrato_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegociacionServer).SolicitarContrato(ctx, req.(*ContratoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Negociacion_AceptarContrato_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegociacionServer).AceptarContrato(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Negociacion_AceptarContrato_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegociacionServer).AceptarContrato(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Negociacion_RechazarContrato_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NegociacionServer).RechazarContrato(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Negociacion_RechazarContrato_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NegociacionServer).RechazarContrato(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Negociacion_ServiceDesc is the grpc.ServiceDesc for Negociacion service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Negociacion_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "negociacion.Negociacion",
	HandlerType: (*NegociacionServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SolicitarContrato",
			Handler:    _Negociacion_SolicitarContrato_Handler,
		},
		{
			MethodName: "AceptarContrato",
			Handler:    _Negociacion_AceptarContrato_Handler,
		},
		{
			MethodName: "RechazarContrato",
			Handler:    _Negociacion_RechazarContrato_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "negociacion.proto",
}
